DROP TABLE IF EXISTS "USER";

CREATE TABLE "USER" (
"id" INT AUTO_INCREMENT  PRIMARY KEY,
"username" VARCHAR(50) NOT NULL UNIQUE,
"password" VARCHAR(50) NOT NULL,
"name" VARCHAR(50) NOT NULL,
"crt_date" TIMESTAMP
);

DROP TABLE IF EXISTS "PASTEBIN";

CREATE TABLE "PASTEBIN" (
"id" INT AUTO_INCREMENT  PRIMARY KEY,
"body" VARCHAR(500),
"user_name" VARCHAR(50) NOT NULL DEFAULT 'GUEST',
"crt_date" TIMESTAMP
);